sudo: true
language:
- python
python:
  - 3.7
before_install:
 - git clone https://github.com/vasiinso/galen-sample-py-tests.git
 - chmod -R +x scripts
 - chmod -R +x ./
install:
 - scripts/install_thrift.sh
 - scripts/install_galenpy.sh
 - pip install -r galen-sample-py-tests/requirements.txt
 - export GRID_URL=https://vasanths:30a91fd1-cc39-4d75-abb1-691e30ff6af9@ondemand.us-west-1.saucelabs.com:443/wd/hub
script: 'scripts/run_tests.sh'
